### ISSUE TITLE
Can't enable gitlab auth

### ISSUE THREAD

**Issue by karlos1337** [Monogramm/docker-taiga#14]
I think have assigned all needed vars and I've restarted the full stack but I can't see any "Gitlab login button" in login section, using the same email/pass that in gitlab neither works and can't see any error on container logs nor browser console, in fact in logs seems all fine:
 ```sh
# Backend logs
Taiga contrib GitLab Auth enabled
```
```sh
# Frontend lgos
Updating Taiga Front contribution plugins list: 'gitlab-auth cookie-warning'
Updating Taiga Front GitLab client id and URL: https://gitlab.****.*** - c279****25eaf
```

```sh
# From back container
env | grep -i gitlab

TAIGA_GITLAB_AUTH_URL=https://gitlab.****.***
TAIGA_GITLAB_AUTH_CLIENT_ID=c279****25eaf
TAIGA_GITLAB_AUTH_CLIENT_SECRET=7a94****a9aa1
TAIGA_ENABLE_GITLAB_AUTH=True
```

```sh
# From front container
env | grep -i gitlab

TAIGA_CONTRIB_PLUGINS='gitlab-auth cookie-warning'
TAIGA_GITLAB_AUTH_URL=https://gitlab.****.***
TAIGA_GITLAB_AUTH_CLIENT_ID=c279****25eaf
```

In backend logs also appears "Taiga contrib LDAP Auth Ext enabled", despite `TAIGA_ENABLE_LDAP=False`, not sure if could be related or is another bug.

Using 4.2-alpine images

**Comment by madmath03** [comment]
Hello,

Well, regarding LDAP being enabled, you just pointed out an error we will have to fix  : 
https://github.com/Monogramm/docker-taiga/blob/7bc052af40f82aeb45602564ff318dc7c5f0fa70/template/back/local.py#L60-L62

So thanks 👍 and sorry for the blunder 😅 

Regarding your main issue, that's a bit weird...
I did not see any mistakes in the init script and as you mentioned your logs seem good...
Could you check and share the content of the following URL: 
`http://your.taiga.instance/conf.json`

Of course, you can hide all sensitive info. My main point is to check if the `contribPlugins` and gitlab properties have been properly set according to your env properties.

**Comment by karlos1337** [comment]
`contribPlugins` is empty :(

```json
{
    "api": "http://taiga.***.***/api/v1/",
    "eventsUrl": "ws://taiga.***.***/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga", "material-design", "high-contrast"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": 104857600,
    "contribPlugins": [],
    "tribeHost": null,
    "gitLabClientId": "c279****25eaf",
    "gitLabUrl": "https://gitlab.***.***",
    "gitHubClientId": "",
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa", "he"],
    "loginFormType": "normal"
}
```

**Comment by madmath03** [comment]
Got it !
I forgot to escape the `[` and `]` for the sed command so the replacement never occurred:
https://github.com/Monogramm/docker-taiga/blob/e9bd461e9990e17ad2900554c53da24f7f9dcdda/template/front/entrypoint.sh#L158-L160

I will fix it and you will have new docker images in a few hours.

Thanks a lot for reporting that.
